import React, { useEffect, useState } from 'react';
import axios from 'axios';
import { CircleMarker, GeoJSON, MapContainer, TileLayer, useMap } from 'react-leaflet';
import 'leaflet/dist/leaflet.css';
import './index.css';

let spots=[{id:42,x:77.14,y:21.09,score:.91,risk:'High',veg:78,d:14},{id:18,x:77.23,y:21.14,score:.84,risk:'High',veg:72,d:18},{id:51,x:77.31,y:21.18,score:.68,risk:'Medium',veg:59,d:27},{id:89,x:77.4,y:21.23,score:.53,risk:'Medium',veg:48,d:34}];
let line={type:'FeatureCollection',features:[{type:'Feature',properties:{},geometry:{type:'LineString',coordinates:[[77.05,21.05],[77.15,21.1],[77.25,21.15],[77.35,21.2],[77.45,21.25]]}}]};
const col={High:'#ef4444',Medium:'#f59e0b',Low:'#22c55e'};
const Badge=({risk})=><b className={`badge ${risk.toLowerCase()}`}>{risk} priority</b>;
function FitAll(){const map=useMap();useEffect(()=>{const bounds=[];spots.forEach(s=>bounds.push([s.y,s.x]));if(bounds.length)map.fitBounds(bounds,{padding:[24,24],maxZoom:7});},[map]);return null}
function Map({pick}){return <div className="map"><MapContainer center={[22.5,82]} zoom={5} style={{height:'100%',width:'100%'}}><TileLayer url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" attribution="&copy; OpenStreetMap contributors"/><GeoJSON data={line} style={{color:'#55a66a',weight:10,opacity:.15}}/><GeoJSON data={line} style={{color:'#172a3a',weight:2}}/>{spots.map(s=><CircleMarker key={s.id} center={[s.y,s.x]} radius={s.risk==='High'?5:3} pathOptions={{color:'#fff',weight:1,fillColor:col[s.risk],fillOpacity:.82}} eventHandlers={{click:()=>pick(s)}}/>)}<FitAll/></MapContainer></div>}
function Overview({pick}){return <><div className="kpis"><article><p>Active corridors</p><strong>12</strong><small>Across central region</small></article><article className="alert"><p>High priority</p><strong>18</strong><small>Require inspection</small></article><article><p>Under observation</p><strong>47</strong><small>Medium risk locations</small></article><article><p>Inspected</p><strong>124</strong><small>This reporting cycle</small></article></div><section className="card"><div className="card-title"><div><p className="eyebrow">Spatial risk assessment</p><h2>Risk overview map</h2></div></div><Map pick={pick}/></section><div className="two"><section className="card list"><h2>Top priorities</h2>{spots.slice(0,3).map((s,i)=><button onClick={()=>pick(s)} key={s.id}>#{i+1} LOC-{s.id}<Badge risk={s.risk}/></button>)}</section><section className="card activity"><h2>Recent changes</h2><p>Vegetation coverage increased 18%</p><p>6 new hotspots detected</p><p>2 inspections completed</p></section></div></>}
function Explorer({pick}){return <><div className="filters"><div><label>Corridor</label><select><option>Central 400 kV corridor</option></select></div><div><label>Date</label><select><option>Current analysis</option></select></div><div><label>Risk</label><select><option>All priorities</option></select></div></div><div className="explorer"><aside className="filter-panel"><p className="eyebrow">Filters</p><h3>Risk</h3>{['High','Medium','Low'].map(x=><label className="check" key={x}><input type="checkbox" defaultChecked={x!=='Low'}/>{x}</label>)}<h3>Map layers</h3>{['Transmission line','Towers','Corridor boundary','Vegetation','Risk heatmap','Hotspots','Land cover','Historical change'].map((x,i)=><label className="check" key={x}><input type="checkbox" defaultChecked={i<6}/>{x}</label>)}</aside><section className="card"><div className="card-title"><div><p className="eyebrow">Interactive GIS map</p><h2>Corridor explorer</h2></div></div><Map pick={pick}/></section></div></>}
function Details({spot,inspect}){return <><button className="back">← Back to map</button><section className="card details-page"><div className="detail-hero"><div><p className="eyebrow">Location #{spot.id}</p><h1>Vegetation risk alert</h1><Badge risk={spot.risk}/></div><div className="big-score">Priority score<strong>{spot.score.toFixed(2)}</strong></div></div><div className="metric-row">{[['NDVI','0.71'],['Vegetation density',`${spot.veg}%`],['Growth trend','+32%'],['Distance to line',`${spot.d} m`],['Model confidence','92%']].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</div><h2>Why was this flagged?</h2>{[['Vegetation density',spot.veg],['Growth trend',92],['Proximity',88]].map(x=><div className="reason" key={x[0]}><span>{x[0]}</span><div><i style={{width:`${x[1]}%`}}/></div><b>{x[1]}%</b></div>)}<h2>Evidence</h2><div className="evidence-tabs"><button>Current image</button><button>Previous</button><button>NDVI</button><button>Vegetation mask</button></div><button className="primary" onClick={inspect}>Mark for inspection</button></section></>}
function Priorities({pick}){return <section className="card ranking"><div className="card-title"><div><p className="eyebrow">Action queue</p><h1>Inspection priority</h1></div><button className="export">Export ↗</button></div><div className="table-head"><span>Location</span><span>Priority</span><span>Growth</span><span>Distance</span><span>Action</span></div>{spots.map((s,i)=><button className="row" key={s.id} onClick={()=>pick(s)}><span><b>{i+1}</b> LOC-{s.id}</span><Badge risk={s.risk}/><span>+{32-i*3}%</span><span>{s.d} m</span><span>View details →</span></button>)}</section>}
function Analytics(){return <><section className="card chart"><p className="eyebrow">Temporal analysis</p><h1>Vegetation change</h1><div className="chart-area"><svg viewBox="0 0 600 210" preserveAspectRatio="none"><path d="M15 180 L150 145 L290 112 L430 67 L580 29" fill="none" stroke="#13855f" strokeWidth="5"/><path d="M15 180 L150 145 L290 112 L430 67 L580 29 L580 210 L15 210Z" fill="#dff3e8"/></svg></div></section><div className="three"><article className="card"><p>Current NDVI</p><strong>0.71</strong></article><article className="card"><p>Previous NDVI</p><strong>0.54</strong></article><article className="card"><p>Change</p><strong>+0.17</strong></article></div></>}
function Evidence(){return <><section className="card"><div className="card-title"><div><p className="eyebrow">Location #042</p><h1>Evidence comparison</h1></div><Badge risk="High"/></div><div className="evidence-grid">{['Current image','Previous image','NDVI','Vegetation mask'].map((x,i)=><div className={`image im${i}`} key={x}><b>{x}</b><span>{i===0?'18 Aug 2026':'Analysis evidence'}</span></div>)}</div></section><section className="card conclusion"><p className="eyebrow">Change detected</p><h2>Vegetation increased by 23%</h2><p>Increasing vegetation and strong proximity signal make this a high-priority inspection.</p></section></>}
export default function App(){const pages=['Overview','Corridor explorer','Hotspot details','Inspection priorities','Analytics','Evidence'];const [page,setPage]=useState('Overview'),[spot,setSpot]=useState(spots[0]),[,rerender]=useState(0);useEffect(()=>{const load=([hotspots,lines])=>{const records=(hotspots.data.features||[]).map(f=>({id:f.id,x:f.geometry.coordinates[0],y:f.geometry.coordinates[1],score:f.properties.risk_score,risk:f.properties.risk_category,veg:Math.round((f.properties.vegetation_fraction||0)*100),d:f.properties.mean_dist_to_line_m}));if(records.length){spots=records;line=lines.data;setSpot(records[0]);rerender(x=>x+1)}};Promise.all([axios.get('/hotspots',{params:{limit:2000}}),axios.get('/transmission-lines')]).then(load).catch(()=>Promise.all([axios.get('/data/hotspots.geojson'),axios.get('/data/transmission-lines.geojson')]).then(load).catch(()=>{}));},[]);const pick=s=>{setSpot(s);setPage('Hotspot details')};const view=page==='Overview'?<Overview pick={pick}/>:page==='Corridor explorer'?<Explorer pick={pick}/>:page==='Hotspot details'?<Details spot={spot} inspect={()=>alert('Location marked for inspection')}/>:page==='Inspection priorities'?<Priorities pick={pick}/>:page==='Analytics'?<Analytics/>:<Evidence/>;return <main className="shell"><aside className="sidebar"><div className="brand"><i>ϟ</i><span>Corridor<br/><b>Intelligence</b></span></div><nav>{pages.map(x=><button key={x} className={page===x?'active':''} onClick={()=>setPage(x)}>{x}</button>)}</nav><div className="status"><span/> SIH India data loaded<small>{spots.length} locations · {line.features.length} lines</small></div></aside><section className="workspace"><header><div><p className="eyebrow">Network operations / India</p><h1>{page}</h1></div><div className="head-actions"><button onClick={()=>window.location.reload()}>↻</button><b>SG</b></div></header>{view}</section></main>}
